directory: ~/Music
library: ~/.config/beets/musiclibrary.db
# accept mathches with similarity of 90% and above
match: 
  strong_rec_thresh: 0.10 # (default: 0.04)
import:
  copy: no
  write: yes
  move: yes
plugins:
  fetchart lastgenre zero fish edit scrub info discogs mpdupdate mbsubmit
play:
  command: mpc add
  raw: yes
lastgenre:
  count: 3
  prefer_specific: yes
paths:
    default: $albumartist — $album ($year)/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
# assume the release date of the original release
original_date: yes
zero:
  fields: month day comments lyrics images albumartist_sort albumartist_credit albumartist_credit arranger artist_sort composer_sort acoustid_fingerprint acoustid_id bpm rg_album_gain catalognum rg_album_peak
  update_databese: true
fetchart:
  auto: yes
  cover_format: JPEG
  enforce_ratio: 8% # devation from 1:1
clutter:
  - "Thumbs.DB"
  - "Thumbs.db"
  - "thumbs.db"
  - ".DS_Store"
  - "*.svf"
  - "*.m3u"
  - "*.cue"
  - "*.log"
mpd:
  host: /run/user/1000/mpd/socket

  
