directory: ~/Music
library: ~/Music/musiclibrary.db
import:
  copy: no
  write: yes
  move: yes
plugins:
  fetchart lastgenre zero fish edit scrub info discogs play random
play:
  command: amberol
lastgenre:
  count: 3
paths:
    default: $albumartist — $album ($year)/$track $title
    singleton: Non-Album/$artist/$title
    comp: Compilations/$album%aunique{}/$track $title
# assume the release date of the original release
original_date: yes
zero:
  fields: month day comments lyrics images albumartist_sort albumartist_credit albumartist_credit arranger artist_sort composer_sort acoustid_fingerprint acoustid_id  bpm rg_album_gain catalognum rg_album_peak
  update_databese: true
fetchart:
  auto: yes
clutter:
  - "Thumbs.DB"
  - "Thumbs.db"
  - "thumbs.db"
  - ".DS_Store"
  - "*.svf"
  - "*.m3u"
  - "*.cue"
  - "*.log"
